"""
Pytest configuration and shared fixtures.
"""

import os
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest


@pytest.fixture
def temp_dir():
    """Provide a temporary directory that is cleaned up after the test."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_config_dir(temp_dir):
    """Create a sample configuration directory structure."""
    config_dir = temp_dir / "config"
    (config_dir / "robots").mkdir(parents=True)
    (config_dir / "processes").mkdir(parents=True)
    (config_dir / "tools").mkdir(parents=True)

    # Create sample robot config
    robot_config = """
robot:
  name: "Test Robot"
  manufacturer: "Test Manufacturer"
  type: "industrial_arm"

kinematics:
  base_frame: "base_link"
  tool_frame: "tool0"
  home_position: [0.0, -0.5, 0.5, 0.0, -0.5, 0.0]

limits:
  joints:
    joint_1:
      lower: -180
      upper: 180
"""
    (config_dir / "robots" / "test_robot.yaml").write_text(robot_config)

    # Create sample process config
    process_config = """
process:
  name: "Test Process"
  type: "waam"

parameters:
  wire_feed_rate: 8.0
  travel_speed: 10.0

slicing:
  layer_height: 2.5
  bead_width: 6.0
"""
    (config_dir / "processes" / "test_waam.yaml").write_text(process_config)

    # Create sample tool config
    tool_config = """
tool:
  name: "Test Milling Tool"
  type: "milling"
  urdf_path: "urdf/tools/milling_tool.urdf"
  tcp_offset: [0, 0, 0.15, 0, 0, 0]
  mass: 2.0
  description: "Test milling tool"

properties:
  diameter: 6.0
  rotation_speed: 10000
  number_of_teeth: 4
"""
    (config_dir / "tools" / "test_mill.yaml").write_text(tool_config)

    return config_dir


# ── ORNL Slicer 2 mock for CI ────────────────────────────────────────────────
# When the ORNL Slicer 2 binary is not installed (e.g. in CI), this fixture
# patches the subprocess wrapper to return canned G-code output so that the
# full slicing pipeline can be tested without the external binary.

_SAMPLE_GCODE = """\
; Generated by OpenAxis ORNL mock
; ORNL Slicer 2 v1.3.001
;BEGINNING LAYER: 0
;TYPE:PERIMETER
G1 X0.000 Y0.000 Z0.200 E1.0 F1000
G1 X10.000 Y0.000 Z0.200 E1.0
G1 X10.000 Y10.000 Z0.200 E1.0
G1 X0.000 Y10.000 Z0.200 E1.0
G1 X0.000 Y0.000 Z0.200 E1.0
;TYPE:INFILL
G1 X1.000 Y1.000 Z0.200 E1.0
G1 X9.000 Y1.000 Z0.200 E1.0
G1 X9.000 Y9.000 Z0.200 E1.0
G1 X1.000 Y9.000 Z0.200 E1.0
;BEGINNING LAYER: 1
;TYPE:PERIMETER
G1 X0.000 Y0.000 Z0.400 E1.0
G1 X10.000 Y0.000 Z0.400 E1.0
G1 X10.000 Y10.000 Z0.400 E1.0
G1 X0.000 Y10.000 Z0.400 E1.0
G1 X0.000 Y0.000 Z0.400 E1.0
;TYPE:INFILL
G1 X1.000 Y1.000 Z0.400 E1.0
G1 X9.000 Y9.000 Z0.400 E1.0
"""


@pytest.fixture
def mock_ornl_slicer(tmp_path):
    """Mock the ORNL Slicer 2 subprocess for CI environments.

    Patches ``find_slicer_executable`` to return a fake binary path
    and ``subprocess.run`` to write canned G-code output. This enables
    full integration testing of the slicing pipeline in CI without
    installing the ORNL Slicer 2 binary.

    Usage::

        def test_slicing(mock_ornl_slicer):
            from openaxis.slicing.ornl_slicer import ORNLSlicer
            slicer = ORNLSlicer()
            toolpath = slicer.slice("model.stl")
    """
    fake_exe = str(tmp_path / "slicer2_cli.exe")
    Path(fake_exe).touch()  # Create a dummy file so os.path.isfile passes

    def _fake_subprocess_run(cmd, **kwargs):
        """Write canned G-code to the output directory specified in --output_location."""
        output_dir = None
        for i, arg in enumerate(cmd):
            if arg == "--output_location" and i + 1 < len(cmd):
                output_dir = cmd[i + 1]
                break

        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
            # ORNL writes <output_dir>.gcode adjacent to the output dir
            gcode_path = output_dir.rstrip(os.sep) + ".gcode"
            with open(gcode_path, "w") as f:
                f.write(_SAMPLE_GCODE)

        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = "Slicing complete (mock)"
        mock_result.stderr = ""
        return mock_result

    with patch("openaxis.slicing.ornl_slicer.find_slicer_executable", return_value=fake_exe), \
         patch("openaxis.slicing.ornl_slicer.subprocess.run", side_effect=_fake_subprocess_run):
        yield fake_exe


@pytest.fixture
def sample_project(temp_dir):
    """Create a sample project."""
    from openaxis.core.project import Project

    project_dir = temp_dir / "test_project"
    project = Project.create(
        name="Test Project",
        path=project_dir,
        description="A test project",
        author="Test Author",
    )
    return project
