"""
Tests for G-code generation module.
"""

from pathlib import Path
import tempfile

import pytest
from compas.geometry import Point

from openaxis.slicing.gcode import GCodeConfig, GCodeFlavor, GCodeGenerator
from openaxis.slicing.toolpath import Toolpath, ToolpathSegment, ToolpathType


class TestGCodeConfig:
    """Tests for GCodeConfig."""

    def test_default_initialization(self):
        """Test default configuration."""
        config = GCodeConfig()

        assert config.flavor == GCodeFlavor.GENERIC
        assert config.use_relative_extrusion is False
        assert config.feedrate_multiplier == 1.0
        assert config.extrusion_multiplier == 1.0

    def test_custom_initialization(self):
        """Test custom configuration."""
        config = GCodeConfig(
            flavor=GCodeFlavor.MARLIN,
            use_relative_extrusion=True,
            feedrate_multiplier=1.5,
        )

        assert config.flavor == GCodeFlavor.MARLIN
        assert config.use_relative_extrusion is True
        assert config.feedrate_multiplier == 1.5


class TestGCodeGenerator:
    """Tests for GCodeGenerator."""

    def test_initialization(self):
        """Test generator initialization."""
        generator = GCodeGenerator()

        assert generator.config is not None
        assert generator.current_position == [0.0, 0.0, 0.0]
        assert generator.current_extrusion == 0.0

    def test_generate_empty_toolpath(self):
        """Test generating G-code from empty toolpath."""
        toolpath = Toolpath(layer_height=1.0)
        generator = GCodeGenerator()

        gcode = generator.generate(toolpath)

        assert isinstance(gcode, str)
        assert len(gcode) > 0
        assert "Generated by OpenAxis" in gcode
        assert "G28" in gcode  # Home command

    def test_generate_with_segments(self):
        """Test generating G-code with segments."""
        toolpath = Toolpath(layer_height=1.0)

        segment = ToolpathSegment(
            points=[Point(0, 0, 0), Point(10, 0, 0), Point(10, 10, 0)],
            type=ToolpathType.PERIMETER,
            layer_index=0,
            extrusion_width=1.0,
            speed=50.0,
        )

        toolpath.add_segment(segment)
        generator = GCodeGenerator()

        gcode = generator.generate(toolpath)

        assert "PERIMETER" in gcode
        assert "G1 X10.000 Y0.000 Z0.000" in gcode
        assert "G1 X10.000 Y10.000 Z0.000" in gcode

    def test_generate_with_file_output(self):
        """Test generating G-code and writing to file."""
        toolpath = Toolpath(layer_height=1.0)

        segment = ToolpathSegment(
            points=[Point(0, 0, 0), Point(10, 0, 0)],
            type=ToolpathType.PERIMETER,
            layer_index=0,
        )

        toolpath.add_segment(segment)
        generator = GCodeGenerator()

        with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".gcode") as f:
            output_path = Path(f.name)

        try:
            gcode = generator.generate(toolpath, output_path)

            # Check file was created
            assert output_path.exists()

            # Check file contents
            file_contents = output_path.read_text(encoding="utf-8")
            assert file_contents == gcode
            assert "Generated by OpenAxis" in file_contents
        finally:
            # Clean up
            if output_path.exists():
                output_path.unlink()

    def test_relative_extrusion(self):
        """Test G-code generation with relative extrusion."""
        config = GCodeConfig(use_relative_extrusion=True)
        generator = GCodeGenerator(config)

        toolpath = Toolpath(layer_height=1.0)
        segment = ToolpathSegment(
            points=[Point(0, 0, 0), Point(10, 0, 0)],
            type=ToolpathType.PERIMETER,
            layer_index=0,
        )
        toolpath.add_segment(segment)

        gcode = generator.generate(toolpath)

        assert "M83" in gcode  # Relative extrusion command

    def test_absolute_extrusion(self):
        """Test G-code generation with absolute extrusion."""
        config = GCodeConfig(use_relative_extrusion=False)
        generator = GCodeGenerator(config)

        toolpath = Toolpath(layer_height=1.0)
        segment = ToolpathSegment(
            points=[Point(0, 0, 0), Point(10, 0, 0)],
            type=ToolpathType.PERIMETER,
            layer_index=0,
        )
        toolpath.add_segment(segment)

        gcode = generator.generate(toolpath)

        assert "M82" in gcode  # Absolute extrusion command

    def test_header_generation(self):
        """Test header generation."""
        toolpath = Toolpath(
            layer_height=2.0,
            total_layers=10,
            process_type="WAAM",
            material="steel",
        )

        generator = GCodeGenerator()
        gcode = generator.generate(toolpath)

        # Check header metadata
        assert "Process: WAAM" in gcode
        assert "Material: steel" in gcode
        assert "Total layers: 10" in gcode
        assert "Layer height: 2.0 mm" in gcode

    def test_footer_generation(self):
        """Test footer generation."""
        toolpath = Toolpath(layer_height=1.0)
        generator = GCodeGenerator()

        gcode = generator.generate(toolpath)

        # Check footer commands
        assert "M104 S0" in gcode  # Turn off hotend
        assert "M84" in gcode  # Disable motors
        assert "Print complete" in gcode

    def test_custom_start_gcode(self):
        """Test custom start G-code."""
        config = GCodeConfig(start_gcode="G29 ; Auto bed leveling")
        generator = GCodeGenerator(config)

        toolpath = Toolpath(layer_height=1.0)
        gcode = generator.generate(toolpath)

        assert "G29 ; Auto bed leveling" in gcode

    def test_custom_end_gcode(self):
        """Test custom end G-code."""
        config = GCodeConfig(end_gcode="M300 S1000 P500 ; Beep")
        generator = GCodeGenerator(config)

        toolpath = Toolpath(layer_height=1.0)
        gcode = generator.generate(toolpath)

        assert "M300 S1000 P500 ; Beep" in gcode

    def test_feedrate_multiplier(self):
        """Test feedrate multiplier."""
        config = GCodeConfig(feedrate_multiplier=2.0)
        generator = GCodeGenerator(config)

        toolpath = Toolpath(layer_height=1.0)
        segment = ToolpathSegment(
            points=[Point(0, 0, 0), Point(10, 0, 0)],
            type=ToolpathType.PERIMETER,
            layer_index=0,
            speed=50.0,  # 50 mm/s
        )
        toolpath.add_segment(segment)

        gcode = generator.generate(toolpath)

        # 50 mm/s * 60 s/min * 2.0 multiplier = 6000 mm/min
        assert "F6000" in gcode

    def test_move_command(self):
        """Test move command generation."""
        generator = GCodeGenerator()

        move_cmd = generator._move(10.5, 20.5, 30.5, rapid=True)

        assert "G0" in move_cmd
        assert "X10.500" in move_cmd
        assert "Y20.500" in move_cmd
        assert "Z30.500" in move_cmd

    def test_extrude_command(self):
        """Test extrusion command generation."""
        generator = GCodeGenerator()

        extrude_cmd = generator._extrude(10.0, 20.0, 30.0, 5.0, 3000.0)

        assert "G1" in extrude_cmd
        assert "X10.000" in extrude_cmd
        assert "Y20.000" in extrude_cmd
        assert "Z30.000" in extrude_cmd
        assert "E" in extrude_cmd
        assert "F3000" in extrude_cmd
