"""
Fanuc LS Post Processor — generates .ls files for Fanuc controllers.

Outputs J/L instructions with CNT blending, speed in mm/sec.
"""

from typing import Any, Dict, List, Optional

from .base import PostProcessorBase, PostProcessorConfig, PointData


class FanucPostProcessor(PostProcessorBase):
    """Fanuc LS post processor generating .ls files."""

    def __init__(self, config: Optional[PostProcessorConfig] = None):
        cfg = config or PostProcessorConfig(
            format_name='fanuc',
            file_extension='.ls',
            comment_prefix='! ',
            speed_units='mm/sec',
            blending=50.0,  # CNT value 0-100
            tool_name='UTOOL[1]',
            work_object='UFRAME[1]',
        )
        super().__init__(cfg)
        self._line_num = 0
        self._point_num = 0

    def _next_line(self) -> int:
        self._line_num += 1
        return self._line_num

    def _next_point(self) -> int:
        self._point_num += 1
        return self._point_num

    def comment(self, text: str) -> str:
        return f"   ! {text} ;"

    def _position(self, pt: PointData) -> str:
        """Format a Fanuc position."""
        pn = self._next_point()
        return f"P[{pn}:{pt.x:.2f},{pt.y:.2f},{pt.z:.2f},180.0,0.0,0.0]"

    def header(self, toolpath_data: Dict[str, Any]) -> List[str]:
        name = self.config.program_name
        total_layers = toolpath_data.get('totalLayers', 0)
        total_points = toolpath_data.get('statistics', {}).get('totalPoints', 0)

        lines = [
            f"/PROG  {name}",
            f"/ATTR",
            f"OWNER\t\t= MNEDITOR;",
            f"COMMENT\t\t= \"OpenAxis Generated\";",
            f"PROG_SIZE\t= 0;",
            f"CREATE\t\t= DATE;",
            f"DEFAULT_GROUP\t= 1,*,*,*,*;",
            f"CONTROL_CODE\t= 00000000 00000000;",
            f"/MN",
            f"   ! Generated by OpenAxis Post Processor ;",
            f"   ! Layers: {total_layers}, Points: {total_points} ;",
            f"   ! Format: Fanuc LS ;",
        ]
        self._line_num = 0
        self._point_num = 0

        # Setup
        ln = self._next_line()
        lines.append(f"   {ln}:  {self.config.tool_name} ;")
        ln = self._next_line()
        lines.append(f"   {ln}:  {self.config.work_object} ;")

        return lines

    def footer(self) -> List[str]:
        ln = self._next_line()
        lines = [
            f"   ! Program complete ;",
            f"   {ln}:  J P[1] 50% FINE ;",
            f"/POS",
            f"/END",
        ]
        return lines

    def linear_move(self, pt: PointData) -> List[str]:
        ln = self._next_line()
        speed = pt.speed  # mm/sec
        cnt = int(self.config.blending)
        pos = self._position(pt)
        return [
            f"   {ln}:L {pos} {speed:.0f}mm/sec CNT{cnt} ;",
        ]

    def rapid_move(self, pt: PointData) -> List[str]:
        ln = self._next_line()
        pos = self._position(pt)
        return [
            f"   {ln}:J {pos} 100% FINE ;",
        ]

    def process_on_code(self, pt: PointData) -> List[str]:
        ln = self._next_line()
        return [
            f"   ! Process ON ;",
            f"   {ln}:  DO[1:ProcessOn]=ON ;",
        ]

    def process_off_code(self, pt: PointData) -> List[str]:
        ln = self._next_line()
        return [
            f"   ! Process OFF ;",
            f"   {ln}:  DO[1:ProcessOn]=OFF ;",
        ]

    def layer_change_code(self, layer: int) -> List[str]:
        return [
            f"",
            f"   ! ===== Layer {layer} =====",
        ]
