"""
Configurable G-code Post Processor — enhanced replacement for basic gcode.py.

Supports:
- Full event hook system
- Configurable retraction, Z-hop, extrusion tracking
- Process type-specific defaults (WAAM, pellet extrusion, milling)
- G92/M82/M83 extrusion mode selection
"""

from typing import Any, Dict, List, Optional

from .base import PostProcessorBase, PostProcessorConfig, PointData


class GCodePostProcessor(PostProcessorBase):
    """
    Configurable G-code post processor.

    Generates standard G-code with full customization via event hooks.
    Tracks extrusion distance and supports retraction/z-hop.
    """

    def __init__(self, config: Optional[PostProcessorConfig] = None):
        cfg = config or PostProcessorConfig(
            format_name='gcode',
            file_extension='.gcode',
            comment_prefix='; ',
            speed_units='mm/min',
            default_speed=1000.0,
            travel_speed=5000.0,
        )
        super().__init__(cfg)

        # G-code specific state
        self._extrusion: float = 0.0
        self._current_z: float = 0.0
        self._retract_dist: float = 2.0
        self._z_hop: float = 0.5
        self._extrusion_width: float = 0.6
        self._layer_height: float = 0.3
        self._absolute_extrusion: bool = True
        self._prev_x: float = 0.0
        self._prev_y: float = 0.0

    def comment(self, text: str) -> str:
        return f"; {text}"

    def header(self, toolpath_data: Dict[str, Any]) -> List[str]:
        import datetime

        self._layer_height = toolpath_data.get('layerHeight', 0.3)
        total_layers = toolpath_data.get('totalLayers', 0)
        total_points = toolpath_data.get('statistics', {}).get('totalPoints', 0)
        process_type = toolpath_data.get('processType', 'unknown')

        lines = [
            f"; Generated by OpenAxis Post Processor",
            f"; Date: {datetime.datetime.now().isoformat()}",
            f"; Process: {process_type}",
            f"; Layers: {total_layers}",
            f"; Layer Height: {self._layer_height:.3f} mm",
            f"; Points: {total_points}",
            f"",
            f"; --- Initialization ---",
            f"G21 ; Set units to millimeters",
            f"G90 ; Absolute positioning",
        ]

        if self._absolute_extrusion:
            lines.append("M82 ; Absolute extrusion")
        else:
            lines.append("M83 ; Relative extrusion")

        lines.extend([
            f"G28 ; Home all axes",
            f"G92 E0 ; Reset extruder",
            f"",
        ])

        self._extrusion = 0.0
        self._current_z = 0.0
        self._prev_x = 0.0
        self._prev_y = 0.0

        return lines

    def footer(self) -> List[str]:
        lines = [
            f"",
            f"; --- End G-code ---",
            f"G1 E{self._extrusion - self._retract_dist:.4f} F{40 * 60:.0f} ; Final retract",
            f"G0 Z{self._current_z + 10:.3f} ; Raise Z",
            f"G28 X Y ; Home X/Y",
            f"M84 ; Disable motors",
            f"; OpenAxis export complete",
        ]
        return lines

    def linear_move(self, pt: PointData) -> List[str]:
        # Calculate extrusion distance
        dx = pt.x - self._prev_x
        dy = pt.y - self._prev_y
        dist = (dx ** 2 + dy ** 2) ** 0.5

        self._extrusion += dist * self._extrusion_width * self._layer_height / 10.0
        self._prev_x = pt.x
        self._prev_y = pt.y

        speed = pt.speed
        if self.config.speed_units == 'mm/s':
            speed = pt.speed * 60  # Convert to mm/min for G-code

        z_str = f" Z{pt.z:.3f}" if abs(pt.z - self._current_z) > 0.001 else ""
        self._current_z = pt.z

        return [
            f"G1 X{pt.x:.3f} Y{pt.y:.3f}{z_str} E{self._extrusion:.4f} F{speed:.0f}",
        ]

    def rapid_move(self, pt: PointData) -> List[str]:
        self._prev_x = pt.x
        self._prev_y = pt.y
        self._current_z = pt.z

        return [
            f"G0 X{pt.x:.3f} Y{pt.y:.3f} Z{pt.z:.3f}",
        ]

    def process_on_code(self, pt: PointData) -> List[str]:
        return [
            f"; Process ON",
            f"G1 E{self._extrusion:.4f} F{40 * 60:.0f} ; Prime",
        ]

    def process_off_code(self, pt: PointData) -> List[str]:
        lines = [
            f"; Process OFF",
            f"G1 E{self._extrusion - self._retract_dist:.4f} F{40 * 60:.0f} ; Retract",
        ]
        if self._z_hop > 0:
            lines.append(f"G0 Z{self._current_z + self._z_hop:.3f} ; Z-hop")
        return lines

    def layer_change_code(self, layer: int) -> List[str]:
        new_z = layer * self._layer_height
        lines = [
            f"",
            f"; ===== Layer {layer} (Z={new_z:.3f}) =====",
        ]
        if abs(new_z - self._current_z) > 0.001:
            lines.append(f"G0 Z{new_z:.3f}")
            self._current_z = new_z
        return lines
