"""
KUKA KRL Post Processor — generates .src files for KUKA KRC controllers.

Outputs LIN/PTP instructions with velocity, C_DIS/C_VEL blending parameters.
"""

from typing import Any, Dict, List, Optional

from .base import PostProcessorBase, PostProcessorConfig, PointData


class KRLPostProcessor(PostProcessorBase):
    """KUKA KRL post processor generating .src files."""

    def __init__(self, config: Optional[PostProcessorConfig] = None):
        cfg = config or PostProcessorConfig(
            format_name='krl',
            file_extension='.src',
            comment_prefix='; ',
            speed_units='mm/s',
            blending=5.0,
            tool_name='TOOL_DATA[1]',
            work_object='BASE_DATA[1]',
        )
        super().__init__(cfg)

    def comment(self, text: str) -> str:
        return f"  ; {text}"

    def _frame(self, pt: PointData) -> str:
        """Format a KUKA frame {X, Y, Z, A, B, C}."""
        return f"{{X {pt.x:.2f}, Y {pt.y:.2f}, Z {pt.z:.2f}, A 0.0, B 180.0, C 0.0}}"

    def header(self, toolpath_data: Dict[str, Any]) -> List[str]:
        name = self.config.program_name
        total_layers = toolpath_data.get('totalLayers', 0)
        total_points = toolpath_data.get('statistics', {}).get('totalPoints', 0)

        lines = [
            f"&ACCESS RVP",
            f"&REL 1",
            f"&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe",
            f"&PARAM EDITMASK = *",
            f"DEF {name}()",
            f"  ; Generated by OpenAxis Post Processor",
            f"  ; Layers: {total_layers}, Points: {total_points}",
            f"  ; Format: KUKA KRL",
            f"",
            f"  ; Initialize",
            f"  $TOOL = {self.config.tool_name}",
            f"  $BASE = {self.config.work_object}",
            f"  $VEL.CP = {self.config.default_speed / 1000:.3f}  ; m/s",
            f"  $APO.CDIS = {self.config.blending:.1f}  ; mm blending",
            f"  BAS(#INITMOV, 0)",
        ]
        return lines

    def footer(self) -> List[str]:
        return [
            f"  ; Program complete",
            f"  PTP $H_POS",
            f"END",
        ]

    def linear_move(self, pt: PointData) -> List[str]:
        frame = self._frame(pt)
        vel = pt.speed / 1000  # mm/s to m/s
        blending = f" C_DIS" if self.config.blending > 0 else ""
        return [
            f"  $VEL.CP = {vel:.3f}",
            f"  LIN {frame}{blending}",
        ]

    def rapid_move(self, pt: PointData) -> List[str]:
        frame = self._frame(pt)
        return [
            f"  PTP {frame} C_DIS",
        ]

    def process_on_code(self, pt: PointData) -> List[str]:
        return [
            f"  ; Process ON",
            f"  $OUT[1] = TRUE",
            f"  WAIT SEC 0.1",
        ]

    def process_off_code(self, pt: PointData) -> List[str]:
        return [
            f"  ; Process OFF",
            f"  $OUT[1] = FALSE",
            f"  WAIT SEC 0.1",
        ]

    def layer_change_code(self, layer: int) -> List[str]:
        return [
            f"",
            f"  ; ===== Layer {layer} =====",
        ]
